apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: spree
        image: <IMAGE_DIGEST>
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-minq
  namespace: default
  labels:
    app: autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: autoscaler
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
